# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0006_newslink_unique_together_slug_startup'),
    ]

    operations = [
        migrations.AlterField('startup', name='tags', field=models.ManyToManyField(to='organizer.Tag', blank=True)),
    ]
